### PR TITLE
feat: added Account Creation Page

### PR DESCRIPTION
**Pull request by MaruthiPothuganti**

### CODE REVIEW

**Review by anshikaa12 — APPROVED** [review]
code looks clean and good to merge

**Review by Ayesha-7 — APPROVED** [review]
good to merge

**Review by GuptaEesh — COMMENTED** [review]
Nothing much to be reviewed.
- HTML structure looks good
- Great use of classes
Good to merge

**Review by aryan-13 — APPROVED** [review]
The code is clean and well-formatted!

**Pull request merged**
